### ISSUE TITLE
PHP 8.0 Bug for PHPCS

### ISSUE THREAD

**Issue by ChrisChasm** [prykon/custom-church-health-plugin#2]
https://github.com/WordPress/WordPress-Coding-Standards/commit/7cd46bed1e6a7a2af3fe24c7f4a044da3076d8f4

**Comment by prykon** [comment]
I downgraded my PHP version. Here's the code for osx hombrew:

```brew install php@7.4
brew unlink php@8.0
brew link php@7.4```
